name: graph-algos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nbdime
  - plotly
  - networkx
  - ipywidgets
  - seaborn
  - imageio
  - numpy
  - pandas
  - matplotlib
  - streamlit
