name: graph-algos
channels:
  - conda-forge
  - defaults
dependencies:
  - nbdime=3.2.1
  - python=3.11.4
  - plotly=5.16.1
  - networkx=3.1
  - ipywidgets=8.1.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - imageio=2.31.1
  - numpy=1.25.2
  - pandas=2.0.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - streamlit=1.25.0
  - jupyterlab=4.0.5
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - jupyterlab_widgets=3.0.8
